### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by Doreenruirui** [UKPLab/coling2016-pcrf-seq2seq#2]
I have got the following error when I run train_complex.sh:

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /home/rui/Package/coling2016-pcrf-seq2seq/src/tmp/train_crf.dat (No such file or directory)
        at marmot.morph.io.FileOptions.getInputStream(FileOptions.java:168)
        at marmot.morph.io.SentenceReader$1.<init>(SentenceReader.java:35)
        at marmot.morph.io.SentenceReader.iterator(SentenceReader.java:31)
        at marmot.morph.cmd.Trainer.train(Trainer.java:33)
        at marmot.morph.cmd.Trainer.main(Trainer.java:72)
Caused by: java.io.FileNotFoundException: /home/rui/Package/coling2016-pcrf-seq2seq/src/tmp/train_crf.dat (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at marmot.morph.io.FileOptions.getInputStream(FileOptions.java:159)

Could you please tell me what is wrong with marmot here ?

**Comment by SteffenEger** [comment]
Hi there,

well, the basic answer is that the file "/home/rui/Package/coling2016-pcrf-seq2seq/src/tmp/train_crf.dat" does not exist. Usually, the file is created in "./makeModel-segmenter-order_complex.sh" in the lines

tmpTrain=tmp/train_crf.dat
./makeAlign-seg_complex.py ${csize} ${csize} < "${input}" > ${tmpTrain}

Is it possible that you're in a directory where there is no tmp/ subdirectory?

**Comment by Doreenruirui** [comment]
Hi Steffen, 

Thank you very much!  I thought it would be created by the code. It works now. Thanks again!

Best,
Rui
